Move and modify behaviour of target_cluster function
open-AIMS/ADRIA.jl pull request #424
Opened 2023-08-17 08:22 UTC by Zapiano

- This function was moved to time_series_clustering.jl file, which makes more sense
- It now returns vector identifying scenarios that belong to target cluster instead of the target cluster index
- It now merges the best cluster with the second one if the number of scenarios inside it is below some threshold

Closes #423 .

2023-08-17 08:28 UTC, ConnectedSystems requested changes
Suggesting minor changes for your review

2023-08-17 08:28 UTC, ConnectedSystems commented on src/analysis/clustering.jl
> +    [c ∈ target_indexes ? 1 : 0 for c in clusters]
I prefer explicit return statements

2023-08-17 08:28 UTC, ConnectedSystems commented on src/analysis/clustering.jl
> +    metric=temporal_variability, size_limit=0.01) where {T<:Int64,F<:Real}
```suggestion
    metric=temporal_variability, size_limit=0.01)::Vector{T} where {T<:Int64,F<:Real}

```

2023-08-17 08:28 UTC, ConnectedSystems commented on src/analysis/clustering.jl
> +- `size_limit` : This function will repeatedely merge the best cluster with the second best
```suggestion
- `size_limit` : This function will iteratively merge the best cluster with the second best

```

2023-08-17 08:28 UTC, ConnectedSystems commented on src/analysis/clustering.jl
> +- `outcomes` : AbstractMatrix of outcomes features
```suggestion
- `outcomes` : AbstractMatrix of scenario outcomes

```

2023-08-17 08:28 UTC, ConnectedSystems commented on src/analysis/clustering.jl
> +- `clusters` : Vector with outcomes cluster indexes
```suggestion
- `clusters` : Vector with outcome cluster indexes

```

2023-08-17 08:28 UTC, ConnectedSystems commented on src/analysis/clustering.jl
> +    target_index = argmax(clusters_statistics)
I think the code is readable enough without having to add a comment.

2023-08-21 00:23 UTC, Zapiano commented
> Suggesting minor changes for your review

I have implemented all your suggestions.

2023-08-21 03:23 UTC, ConnectedSystems commented on src/analysis/clustering.jl
> +        # Nullify targe_index to find the next argmax
```suggestion
        # Nullify target_index to find the next argmax

```

2023-08-21 03:24 UTC, ConnectedSystems commented on src/analysis/clustering.jl
> +    # Merge target cluster if is above 1% of size
```suggestion
    # Merge target cluster if it is above 1% of size

```

Is this meant to be "below 1%"?

2023-08-21 03:24 UTC, ConnectedSystems reviewed
Two minor comments. Will merge once addressed.

2023-08-21 03:27 UTC, Zapiano commented
> Two minor comments. Will merge once addressed.

@ConnectedSystems  done!

2023-08-21 03:27 UTC, Zapiano commented on src/analysis/clustering.jl
> +    # Merge target cluster if is above 1% of size
Yes.

2023-08-21 03:31 UTC, ConnectedSystems approved these changes

2023-08-21 03:31 UTC, merged