Update CSV.write writeheader parameter to header
open-AIMS/ADRIA.jl pull request #506
Opened 2023-09-25 06:42 UTC by Zapiano

As in title.

Closes #503

2023-09-25 11:44 UTC, ConnectedSystems commented on src/Domain.jl
> +    CSV.write(filepath; header=true, append=true)(model_spec(d))
If we're getting rid of the piping anyway...

```suggestion
    CSV.write(filepath, model_spec(d); header=true, append=true)
```

2023-09-25 11:44 UTC, ConnectedSystems commented on src/Domain.jl
>      return
```suggestion
    return nothing
```

2023-09-25 11:45 UTC, ConnectedSystems requested changes
Some minor additional cleanup and adjustment to Blue style

2023-09-26 03:03 UTC, Zapiano commented
@ConnectedSystems  ready for another review.

2023-09-26 04:45 UTC, ConnectedSystems approved these changes
Thank you!

2023-09-26 04:45 UTC, merged