Implement cyclone mortality scenarios
open-AIMS/ADRIA.jl pull request #585
Opened 2023-11-16 06:33 UTC by Zapiano

Load cyclone mortality datacube (using a new data package version) into ADRIA and use it to add coral mortality scenarios caused by cyclones. 

Closes #531 .

2023-11-16 06:36 UTC, Zapiano commented
@ConnectedSystems @Rosejoycrocker 

Note that this is still a draft. The only thing I did so far was load the cyclone datacube.

2023-11-20 05:25 UTC, Zapiano commented
@ConnectedSystems  this is virtually ready but I can't fix the tests as they are broken at the main branch. As you know, I also can't show the results yet (and be 100% sure they make sense) as our scenarios visualization function is also broken. I'm waiting for all of that to be fixed before I finish this.

2023-11-20 08:26 UTC, ConnectedSystems commented
Depends on #589 being merged first.

2023-11-22 00:55 UTC, Zapiano commented
@ConnectedSystems and @Rosejoycrocker  this one is (finally) ready for review. Here is an example of result with 1024 scenarios:

![image](https://github.com/open-AIMS/ADRIA.jl/assets/8040719/927e1f70-4c78-4acc-be94-bdb6cef93a83)

2023-11-22 04:25 UTC, ConnectedSystems requested changes
A few changes necessary.

How do you feel about merging PR #597 into this PR?

Next set of work could be to rename `Example_domain` to `Test_domain`, move it, and include a bunch of checks to that raise error when a malformed Domain is provided by the user?

2023-11-22 04:28 UTC, ConnectedSystems commented
I've added a test that checks the location order but it currently fails as the example geospatial data holds a different set of location names compared to those specified in the netcdf:

These are the ones in the example geospatial data:

```
 "Briggs_BR_C_1"
 "Briggs_BR_OF_1"
 "Briggs_BR_OF_2"
 "Briggs_BR_SS_1"
 "Briggs_BR_S_1"
 "Briggs_BR_S_2"
 "Briggs_BR_S_3"
 "Elford_ER_C_1"
 "Elford_ER_C_10"
 "Elford_ER_C_11"
 "Elford_ER_C_12"
 "Elford_ER_C_2"
 "Elford_ER_C_3"
 "Elford_ER_C_4"
 "Elford_ER_C_5"
 "Elford_ER_C_6"
 "Elford_ER_C_7"
 "Elford_ER_C_8"
 "Elford_ER_C_9"
 "Elford_ER_OF_1"
 "Elford_ER_OF_10"
 "Elford_ER_OF_11"
 "Elford_ER_OF_12"
 "Elford_ER_OF_13"
 "Elford_ER_OF_14"
 "Elford_ER_OF_15"
 "Elford_ER_OF_16"
 "Elford_ER_OF_17"
 "Elford_ER_OF_18"
 "Elford_ER_OF_19"
 "Elford_ER_OF_2"
 "Elford_ER_OF_3"
```

2023-11-22 04:56 UTC, Zapiano commented
> A few changes necessary.
> 
> How do you feel about merging PR #597 into this PR?
> 
> Next set of work could be to rename `Example_domain` to `Test_domain`, move it, and include a bunch of checks to that raise error when a malformed Domain is provided by the user?
> 
> I'm also adding tests to check that handling of cyclone data is correct.

Honestly, I don't think we should or need to merge #597 into this one. They are not directly related, and it's easier/better to do small PRs when possible. I don't see what's the advantage, but I do see some risks.

2023-11-22 05:05 UTC, ConnectedSystems commented on src/ADRIA.jl
> +const COMPAT_DPKG = ["0.3.2-rc"]
Oh actually, I think we should bump to "0.4.0" / "0.4.0-rc"

2023-11-22 05:06 UTC, ConnectedSystems commented
> > A few changes necessary.
> > How do you feel about merging PR #597 into this PR?
> > Next set of work could be to rename `Example_domain` to `Test_domain`, move it, and include a bunch of checks to that raise error when a malformed Domain is provided by the user?
> > I'm also adding tests to check that handling of cyclone data is correct.
> 
> Honestly, I don't think we should or need to merge #597 into this one. They are not directly related, and it's easier/better to do small PRs when possible. I don't see what's the advantage, but I do see some risks.

Well sure, it is two small PRs, it's just one goes into the other. But happy to target main with #597

2023-11-22 05:48 UTC, Zapiano commented on src/ADRIA.jl
> +const COMPAT_DPKG = ["0.3.2-rc"]
About being 0.4.0: I agree, I can update that.

About support 0.3.1: sure. I can update the loading method to handle that.

2023-11-23 03:47 UTC, Zapiano commented
@ConnectedSystems ready for another review :)

2023-11-24 00:59 UTC, ConnectedSystems commented on src/io/inputs.jl
> +    load_cyclone_mortality(data_fn::String)::NamedDimsArray
```suggestion
    load_cyclone_mortality(data_fn::String)::NamedDimsArray
    load_cyclone_mortality(timeframe::Vector{Int64}, site_data::DataFrame)::NamedDimsArray
```

2023-11-24 01:04 UTC, ConnectedSystems commented on src/scenario.jl
> +function _cyclone_mortality(coral_cover, coral_params, cyclone_mortality)::Nothing
I don't think this is a private function as such.

The entire `run_model()` needs a clean up, but the idea would be to separate out each event into their own function and run in order of their envisioned sequence 

For example:

```
shade_locations!()
# ... etc...

bleaching_mortality!()
cyclone_mortality!()
# ... etc...

# run ODE
# ...
```

2023-11-24 01:04 UTC, ConnectedSystems commented on src/scenario.jl
> +function _cyclone_mortality(coral_cover, coral_params, cyclone_mortality)::Nothing
This function modifies in place so by convention it should have the exclamation mark

```suggestion
function _cyclone_mortality!(coral_cover, coral_params, cyclone_mortality)::Nothing
```

2023-11-24 01:05 UTC, ConnectedSystems approved these changes
One minor change after which I'll merge.

Otherwise all tests pass, including the figure generation script.

2023-11-24 09:06 UTC, ConnectedSystems commented
Done.

2023-11-24 09:07 UTC, merged