RME Result Interface
open-AIMS/ADRIA.jl pull request #745
Opened 2024-04-30 07:13 UTC by DanTanAtAims

Results from ReefModEngine.jl can be loaded with the `load_results` function. There are two options depending on the location of the results and accompanying data files. The datafiles in the RME directory can be used as the data directory.

```julia
rs = ADRIA.load_results(RMEResultSet, "<path to data dir>", "<path to results dir>")
```

Expected data directory structure.

```bash
data_dir
│
├───con_bin
│       CONNECT_ACRO_2010_11.bin
│       CONNECT_ACRO_2011_12.bin
│       CONNECT_ACRO_2012_13.bin
│       CONNECT_ACRO_2014_15.bin
│       CONNECT_ACRO_2015_16.bin
│       CONNECT_ACRO_2016_17.bin
│
├───id
│       id_list_2023_03_30.csv
│
└───region
       reefmod_gbr.gpkg
```

The results data directory should contain a `results.nc` NetCDF file and `scenarios.csv`. If
the path to the results directory is not supplied, the results are expected to be
contained in a results subdirectory.

```julia
rs = ADRIA.load_domain(RMEResultSet, "<path to data dir>")
```

Expected data directory structure for defaulted result directory.

```bash
data_dir
├───con_bin
├───id
├───region
└───results
```
Allows access to sensitivity analysis, some of ADRIA metrics and map visualization.

![image](https://github.com/open-AIMS/ADRIA.jl/assets/156630392/857d5659-f16e-487e-b5ac-9bf3dbb088fe)
![image](https://github.com/open-AIMS/ADRIA.jl/assets/156630392/971d3979-07dd-470e-9fe7-959d6fe82439)

2024-05-01 00:00 UTC, ConnectedSystems commented
Hey @DanTanAtAims is this replacing #721 ?

2024-05-01 00:03 UTC, DanTanAtAims commented
> Hey @DanTanAtAims is this replacing #721 ?

Yes, however the C-Scape-Result-Interface will be submitted separately. I'll delete the other pull request.

2024-05-02 01:00 UTC, DanTanAtAims commented
@ConnectedSystems The results interface should now allow for nearly all analysis tools with toy data below. I should update ReefModEngine to export a more complete scenario specification beyond purely intervention factors.

## Time series clustering
<img width="1208" alt="RME_ts_clustering" src="https://github.com/open-AIMS/ADRIA.jl/assets/156630392/75b68912-e9ec-4aaa-ba43-6a13cbbe95d7">

## SIRUS
<img width="1205" alt="RME_SIRUS" src="https://github.com/open-AIMS/ADRIA.jl/assets/156630392/63aca1b8-bbe0-46d8-a7a4-3f7a4ec58fe7">

## Temporal Sensitivity Analysis
<img width="463" alt="RME_TSA" src="https://github.com/open-AIMS/ADRIA.jl/assets/156630392/2851147c-9d09-4751-8f32-9c4728bd2713">

2024-05-02 04:54 UTC, ConnectedSystems commented
Thanks Dan.

I suspect there's a simpler approach we could take compared to reimplementing methods for an RMEResultSet. I'll have to think about it.

2024-05-06 07:49 UTC, ConnectedSystems commented on docs/src/usage/results.md
> +Expected data directory structure for defaulted result directory.
```suggestion
Expected data directory structure for the default result directory is shown below.
```

2024-05-06 07:49 UTC, ConnectedSystems commented on docs/src/usage/results.md
> +Expected data directory structure.
```suggestion
Expected data directory structure:
```

2024-05-06 07:51 UTC, ConnectedSystems commented on src/ADRIA.jl
> +include("io/rme_result_io.jl")
Standardize file name.

Known / established acronyms should always be capitalized (e.g., rme -> RME)

2024-05-06 07:52 UTC, ConnectedSystems commented on docs/src/usage/results.md
> +options depending on the location of the results and accompanying data files.
You state "There are two options" but only mention show one? What is the other option?

2024-05-06 07:54 UTC, ConnectedSystems commented on src/io/rme_result_io.jl
> +    return scenario_groups
Same here: spacing for readability.

Note `return` statements, with very few exceptions, should always be separated for clarity.

```suggestion
    # If the runs do not contain counterfactual or intervened runs exclude the key
    if any(counterfactual_scens)
        scenario_groups[:counterfactual] = counterfactual_scens
    end

    if any(intervened_scens)
        scenario_groups[:intervened] = intervened_scens
    end

    return scenario_groups
```

2024-05-06 07:55 UTC, ConnectedSystems requested changes
Just a few more formatting related changes, but otherwise looks good to me!

2024-05-14 03:45 UTC, DanTanAtAims commented
Rebased branch on to main before merge

2024-05-15 23:29 UTC, ConnectedSystems approved these changes
Thanks, looking good!

2024-05-15 23:29 UTC, merged